spring:
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: https://example.com/.well-known/jwks.json

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
